config/routes.rb
Rails.application.routes.draw do
  root "boards#new"
  resources :boards
  get 'home' => 'boards#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  include Pagy::Backend

  ACTIVERECORD_MAX_INTEGER = 2_147_483_647.freeze

  def self.find_by_id(id)
    Optional.of_nullable(find_by(primary_key => id))
  end

  def self.get_by_id(id)
    find_by_id(id).or_else_raise { ActiveRecord::RecordNotFound.new("Cannot find #{name.demodulize} with id: #{id}") }
  end

  def self.paginate(collection:, page_request: { page: 1, page_size: 10 }, vars: {})
    pagy = Pagy.new(count: collection.count(:all), page: page_request[:page], items: page_request[:page_size], **vars)
    [pagy, collection.offset(pagy.offset).limit(pagy.items)]
  end

  def self.save(record)
    record.tap(&:save)
  end

  def self.save!(record)
    record.tap(&:save!)
  end

  def self.delete!(record)
    record.tap(&:destroy!)
  end
end

app/models/board.rb
class Board < ApplicationRecord
  has_one :board_matrix, foreign_key: :board_id, primary_key: :id

  WIDTH_MIN_SIZE = 2.freeze
  HEIGHT_MIN_SIZE = 2.freeze
  BOMBS_MIN_SIZE = 1.freeze

  def self.get_boards(order_params:, page_request:)
    paginate(
        collection: order(order_params),
        page_request: page_request
    )
  end

  def self.get_recent_boards
    order(created_at: 'desc').limit(10)
  end

  def self.create_new(id: SecureRandom.uuid, email:, name:, width:, height:, bombs:)
    new(id: id, email: email, name: name, width: width, height: height, bombs: bombs)
  end

  def update_board_matrix(board_matrix)
    self.build_board_matrix(matrix: board_matrix)
    self
  end

  def matrix
    self.board_matrix&.matrix
  end
end

app/models/board_matrix.rb
class BoardMatrix < ApplicationRecord
  self.primary_key = :board_id

  belongs_to :board
end

app/controllers/application_controller.rb
require 'util/contract_validator'

class ApplicationController < ActionController::Base
  def initialize(contract_validator: ContractValidator.new)
    super()
    @contract_validator = contract_validator
  end

  def page_params
    params.permit(:page, :page_size)
  end

  def sort_params
    params.permit(:sort, :direction)
  end

  def page_request
    page_params_hash = page_params
    page_params_hash[:page] = page_params_hash[:page].try(&:to_i)
    page_params_hash[:page_size] = page_params_hash[:page_size].try(&:to_i)
    page_params_hash[:page] = 1 unless page_params_hash[:page]
    page_params_hash[:page_size] = 10 unless page_params_hash[:page]

    page_params_hash
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def initialize(board_service: BoardService.new, board_read_service: BoardReadService.new)
    super()
    @board_service = board_service
    @board_read_service = board_read_service
  end

  def home
    @boards = @board_read_service.get_recent_boards
    @table_headers = [
        { label: 'Name' },
        { label: 'Email' },
        { label: 'Generated At' }
    ]
  end

  def index
    @pagy, @boards = @board_read_service.get_boards(order_params: order_params, page_request: page_request)
    @table_headers = [
        { label: 'Name', sort_column: 'name' },
        { label: 'Email', sort_column: 'email' },
        { label: 'Width', sort_column: 'width' },
        { label: 'Height', sort_column: 'height' },
        { label: 'Bombs', sort_column: 'bombs' }
    ]
  end

  def new
    @board = Board.new
  end

  def create
    whitelisted_params = @contract_validator.validate(board_params.to_h, CreateBoardContract.new)
    board = @board_service.create_board(whitelisted_params)

    flash[:success_notice] =  "Board created successfully."
    redirect_to board_path(board)
  rescue ConstraintError => e
    @board = Board.new(board_params.to_h)
    flash[:form_error_notice] = e.messages
    render :new, status: Http::STATUS_UNPROCESSABLE_ENTITY
  end

  def show
    @board = @board_read_service.get_board_by_id(id: params[:id])
  end

  private

  def board_params
    params.require(:board).permit!
  end

  def order_params
    valid_sort_params = @contract_validator.validate(sort_params.to_h, GetBoardsQueryContract.new)
    valid_sort_params[:sort] = 'created_at' unless valid_sort_params[:sort]
    valid_sort_params[:direction] = 'desc' unless valid_sort_params[:direction]
    { valid_sort_params[:sort] => valid_sort_params[:direction] }

  rescue ConstraintError => e
    params.delete(:sort)
    params.delete(:direction)
    flash[:error_notice] = e.messages
    index
    render :index, error_notice: e.messages and return
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def page_params
    params.permit(:page, :page_size)
  end

  def sort_params
    params.permit(:sort, :direction)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
  def sort_link(label:, sort:)
    query_params = {**page_params, data: { turbo_action: 'advance' }}
    link_to(label, boards_path(sort: sort, direction: next_direction(sort), **query_params))
  end

  def next_direction(sort)
    if params[:sort] == sort
      params[:direction] == 'asc' ? 'desc' : 'asc'
    else
      'asc'
    end
  end

  def sort_indicator
    params[:direction] == 'asc' ? arrow_direction = 'up' : arrow_direction = 'down'
    tag.i(class: "fa-solid fa-arrow-#{arrow_direction}")
  end

  def display_date(date)
    date.strftime("%d-%m-%Y %H:%M")
  end
end

app/views/boards/_form.html.erb
<%= render 'shared/form_error_notice' %>
<%= bootstrap_form_for(board, data: { turbo: false }) do |f| %>
  <%= f.email_field :email %>
  <%= f.text_field :name %>
  <%= f.number_field :width %>
  <%= f.number_field :height %>
  <%= f.number_field :bombs %>
  <div class="row">
    <div class="col-6">
      <%= f.submit "Generate Board", class: 'btn btn-primary' %>
    </div>
    <div class="col-6 d-flex align-items-end justify-content-end">
      <%= link_to "Cancel", boards_path, class: "btn btn-danger"%>
    </div>
  </div>
<% end %>

app/views/boards/_grid.html.erb
<div class="table-responsive">
  <table class="table table-bordered" style="table-layout: fixed">
    <tbody>
    <% board.matrix.each do |row| %>
      <tr>
        <% row.each do |col| %>
          <td style="width: 50px; height: 50px" align="center">
            <% if col == "1" %>
              <%= image_tag "/bomb.png" %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/boards/_recent_boards_table.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-striped text-nowrap">
    <thead>
    <% @table_headers.each do |header_info| %>
      <th> <%= header_info[:label] %> </th>
    <% end %>
    </thead>
    <tbody>
    <% boards.each do |board| %>
      <tr>
        <td> <%= link_to board.name, board_path(board.id) %> </td>
        <td> <%= board.email %> </td>
        <td style="width: 15%"> <%= time_tag board.created_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/boards/_table.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-striped text-nowrap">
    <thead>
    <% @table_headers.each do |header_info| %>
      <th>
        <%= sort_link(label: header_info[:label], sort: header_info[:sort_column]) %>
        <%= sort_indicator if params[:sort] == header_info[:sort_column] %>
      </th>
    <% end %>
    </thead>
    <tbody>
    <% boards.each do |board| %>
      <tr>
        <td> <%= link_to board.name, board_path(board.id) %> </td>
        <td> <%= board.email %> </td>
        <td> <%= board.width %> </td>
        <td> <%= board.height %> </td>
        <td style="width: 15%"> <%= board.bombs %> </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/boards/home.html.erb
<h5>Recent Boards</h5>
<% if @boards.empty? %>
  <p>No recent boards.</p>
<% else %>
  <%= render 'recent_boards_table', boards: @boards %>
  <%= link_to 'View All Generated Boards', boards_path, class: "btn btn-primary" %>
<% end %>

app/views/boards/index.html.erb
<h5>Boards Table</h5>
<div class="d-flex align-items-end justify-content-end mb-1">
  <%= link_to "New Board", new_board_path, class: "btn btn-primary btn-lg"%>
</div>
<% if @boards.empty? %>
  <p>No boards available.</p>
<% else %>
  <%= render 'table', boards: @boards, sorting: @sorting %>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/boards/new.html.erb
<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <div class="card">
      <div class="card-header text-center">
        <h1>New Board</h1>
      </div>
      <div class="card-body">
        <%= render "form", board: @board %>
      </div>
    </div>
  </div>
  <div class="col-2"></div>
</div>

app/views/boards/show.html.erb
<div class="row">
  <div class="col-1"></div>
  <div class="col-10">
    <% if @board.matrix.present? %>
      <%= render 'grid', board: @board %>
      <% else %>
      <%= turbo_stream_from "grid_#{@board.id}" %>
      <%= turbo_frame_tag "grid_#{@board.id}" do %>
        <div class="d-flex justify-content-center">
          <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
      <% end %>
    <% end %>
    <h3>Email: <%= @board.email %></h3>
    <h3>Name: <%= @board.name %></h3>
    <h3>Width: <%= @board.width %></h3>
    <h3>Height: <%= @board.height %></h3>
    <h3>Number of Bombs: <%= @board.bombs %></h3>
    <h3>Generated At: <%= time_tag @board.created_at %></h3>
    <hr>
    <%= link_to "Back", boards_path, class: 'btn btn-danger btn-lg mb-5' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinesweeperRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/error_notice' %>
    <%= render 'shared/success_notice' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_notice.html.erb
<% if flash[:error_notice].present? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <% if flash[:error_notice].instance_of?(Array) %>
      <ul>
        <% flash[:error_notice].each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% else %>
      <p> <%= flash[:error_notice] %> </p>
    <% end %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_form_error_notice.html.erb
<% if flash[:form_error_notice].present? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <% if flash[:form_error_notice].instance_of?(Array) %>
      <ul>
        <% flash[:form_error_notice].each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% else %>
      <p> <%= flash[:form_error_notice] %> </p>
    <% end %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <%= link_to 'Minesweeper Rails', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', home_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Boards', boards_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Board', root_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_success_notice.html.erb
<% if flash[:success_notice].present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <% if flash[:success_notice].instance_of?(Array) %>
      <ul>
        <% flash[:success_notice].each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% else %>
      <p> <%= flash[:success_notice] %> </p>
    <% end %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>